# This is a basic workflow to help you get started with Actions

name: Build Latest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Download PAE2
        # You may pin to the exact commit or the version.
        uses: robinraju/release-downloader@v1.1
        with:
          repository: PrototypeTrousers/Applied-Energistics-2
          latest: false
          tag: omni-fixes-v46
          fileName: appliedenergistics2-rv6-stable-7.omni-fixes-v46m.jar
          out-file-path: ./overrides/mods
        
      - name: Download Nutrition
        # You may pin to the exact commit or the version.
        uses: robinraju/release-downloader@v1.1
        with:
          repository: WesCook/Nutrition
          latest: false
          tag: v4.9.0
          fileName: Nutrition-1.12.2-4.9.0.jar
          out-file-path: ./overrides/mods
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: TSRO10-Dev-Build # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./overrides
            ./modlist.html
            ./manifest.json
          # The desired behavior if no files are found using the provided path.
